version: '3'
services:
  protopoll:
    container_name: protopoll
    hostname: protopoll
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: unless-stopped
